export const cards = [
  {
    title: "Overgeared",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 1300000,
    rating: 4.7,
    pages: 150,
    genre: ["Fantasy", "Action"],
    type: "KOMIK",
    label: "top",
    size: "2x2",
    image: "https://i.imgur.com/HHe6hQi.png",
  },
  {
    title: "The Greatest Estate Developer",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 20900,
    rating: 4.7,
    pages: 150,
    genre: ["Comedy"],
    type: "KOMIK",
    label: "choice",
    size: "2x1",
    image: "https://i.imgur.com/essXhcj.png",
  },
  {
    title: "Return Of The Mount Hua Sect",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 1300,
    rating: 4.7,
    pages: 150,
    genre: ["Comedy", "Adventure"],
    type: "NOVEL",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/kyLUJIS.png",
  },
  {
    title: "The Regressed Son Of A Duke Is An Assassin",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 920,
    rating: 4.5,
    pages: 102,
    genre: ["Fantasy", "Drama"],
    type: "KOMIK",
    label: "up",
    size: "1x1",
    image: "https://i.imgur.com/2f3nfuE.png",
  },
  {
    title: "Solo Leveling",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 3000,
    rating: 4.9,
    pages: 220,
    genre: ["Action", "Sci-Fi"],
    type: "KOMIK",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/6IbtPWj.png",
  },
  {
    title: "Solo Max-Level Newbie",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 1300,
    rating: 4.7,
    pages: 150,
    genre: ["Fantasy", "Adventure"],
    type: "KOMIK",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/vU3kZxL.png",
  },
  {
    title: "Reincarnation of the Suicidal Battle God",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 920,
    rating: 4.5,
    pages: 102,
    genre: ["Fantasy", "Drama"],
    type: "NOVEL",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/dMc3mbP.png",
  },
  {
    title: "Damn Reincarnation",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 920,
    rating: 4.5,
    pages: 102,
    genre: ["Fantasy", "Drama"],
    type: "NOVEL",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/58HepWK.png",
  },
  {
    title: "Eleceed",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 3000,
    rating: 4.9,
    pages: 220,
    genre: ["Drama", "Sci-Fi"],
    type: "KOMIK",
    label: "none",
    size: "1x1",
    image: "https://i.imgur.com/5PxKhiM.jpeg",
  },
  {
    title: "Omnicient Reader Viewpoint",
    excerpt:
      "Lorem ipsum dolor sit ameterasu asa  consectetur adipisicing elit. Ea nesciunt eum unde, laborum harum maiores odit id sequi minima officiis eos facilis aliquid libero ex. Eligendi assumenda nesciunt unde ipsa, cupiditate quas, recusandae beatae ad inventore rem corporis odio amet iste cum magnam error nihil quaerat illum quae quibusdam mollitia iure non commodi. Pariatur incidunt laudantium, praesentium nam, eos esse aperiam quidem veniam repudiandae delectus corrupti suscipit aut! Cumque deserunt ipsa tempora cupiditate nobis culpa iusto exercitationem quae adipisci nam. Facilis optio, animi, tempora praesentium nam alias similique est omnis sapiente facere dolorem numquam reiciendis repudiandae aliquid voluptates deserunt harum vel fugit! Consequuntur nam voluptatem nihil doloribus veritatis deleniti, doloremque modi dolor aliquid! Ipsum aliquid id laudantium atque laborum, provident assumenda amet itaque explicabo, impedit minus, dolorum saepe iste magnam numquam ut eaque quos unde asperiores suscipit ad ducimus culpa sed recusandae! Perferendis quaerat sequi quisquam nulla! Saepe, vero aperiam?",
    likes: 3000,
    rating: 4.9,
    pages: 220,
    genre: ["Fantasy", "Sci-Fi"],
    type: "NOVEL",
    label: "new",
    size: "2x1",
    image: "https://upload-os-bbs.hoyolab.com/upload/2024/05/23/365304258/d1adb95d30664a78ff88407d92cac6e2_198581824676022933.jpg",
  }
];
